// Mocks generated by Mockito 5.4.4 from annotations
// in news_app_clean_architecture/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app_clean_architecture/core/resources/data_state.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/auth/domain/entities/user.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/auth/domain/repository/auth_repository.dart'
    as _i3;
import 'package:news_app_clean_architecture/features/user_articles/domain/entities/user_article.dart'
    as _i7;
import 'package:news_app_clean_architecture/features/user_articles/domain/repository/user_article_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.UserEntity?>.empty(),
      ) as _i4.Stream<_i5.UserEntity?>);

  @override
  _i4.Future<_i2.DataState<_i5.UserEntity>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserEntity>>.value(
            _FakeDataState_0<_i5.UserEntity>(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserEntity>>);

  @override
  _i4.Future<_i2.DataState<_i5.UserEntity>> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserEntity>>.value(
            _FakeDataState_0<_i5.UserEntity>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserEntity>>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserEntity?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.UserEntity?>.value(),
      ) as _i4.Future<_i5.UserEntity?>);

  @override
  _i4.Future<_i2.DataState<_i5.UserEntity>> updateProfile({
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.UserEntity>>.value(
            _FakeDataState_0<_i5.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.UserEntity>>);
}

/// A class which mocks [UserArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserArticleRepository extends _i1.Mock
    implements _i6.UserArticleRepository {
  MockUserArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i7.UserArticleEntity>> createArticle(
          _i7.UserArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArticle,
          [article],
        ),
        returnValue: _i4.Future<_i2.DataState<_i7.UserArticleEntity>>.value(
            _FakeDataState_0<_i7.UserArticleEntity>(
          this,
          Invocation.method(
            #createArticle,
            [article],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i7.UserArticleEntity>>);

  @override
  _i4.Future<_i2.DataState<_i7.UserArticleEntity>> updateArticle(
          _i7.UserArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArticle,
          [article],
        ),
        returnValue: _i4.Future<_i2.DataState<_i7.UserArticleEntity>>.value(
            _FakeDataState_0<_i7.UserArticleEntity>(
          this,
          Invocation.method(
            #updateArticle,
            [article],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i7.UserArticleEntity>>);

  @override
  _i4.Future<_i2.DataState<void>> deleteArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [articleId],
        ),
        returnValue:
            _i4.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #deleteArticle,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<_i7.UserArticleEntity>> getArticleById(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.DataState<_i7.UserArticleEntity>>.value(
            _FakeDataState_0<_i7.UserArticleEntity>(
          this,
          Invocation.method(
            #getArticleById,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i7.UserArticleEntity>>);

  @override
  _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>
      getPublishedArticles() => (super.noSuchMethod(
            Invocation.method(
              #getPublishedArticles,
              [],
            ),
            returnValue:
                _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>.value(
                    _FakeDataState_0<List<_i7.UserArticleEntity>>(
              this,
              Invocation.method(
                #getPublishedArticles,
                [],
              ),
            )),
          ) as _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>);

  @override
  _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>> getUserArticles(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArticles,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>.value(
                _FakeDataState_0<List<_i7.UserArticleEntity>>(
          this,
          Invocation.method(
            #getUserArticles,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>);

  @override
  _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>> getArticlesByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesByCategory,
          [category],
        ),
        returnValue:
            _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>.value(
                _FakeDataState_0<List<_i7.UserArticleEntity>>(
          this,
          Invocation.method(
            #getArticlesByCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i7.UserArticleEntity>>>);

  @override
  _i4.Future<_i2.DataState<_i7.UserArticleEntity>> publishArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishArticle,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.DataState<_i7.UserArticleEntity>>.value(
            _FakeDataState_0<_i7.UserArticleEntity>(
          this,
          Invocation.method(
            #publishArticle,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i7.UserArticleEntity>>);

  @override
  _i4.Future<_i2.DataState<_i7.UserArticleEntity>> unpublishArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpublishArticle,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.DataState<_i7.UserArticleEntity>>.value(
            _FakeDataState_0<_i7.UserArticleEntity>(
          this,
          Invocation.method(
            #unpublishArticle,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i7.UserArticleEntity>>);

  @override
  _i4.Future<_i2.DataState<String>> uploadImage(_i8.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [imageFile],
        ),
        returnValue:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFile],
          ),
        )),
      ) as _i4.Future<_i2.DataState<String>>);
}
