// Mocks generated by Mockito 5.4.4 from annotations
// in news_app_clean_architecture/test/mocks/mock_data_sources.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:news_app_clean_architecture/features/auth/data/data_sources/remote/auth_remote_data_source.dart'
    as _i4;
import 'package:news_app_clean_architecture/features/auth/data/models/user_model.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/user_articles/data/data_sources/remote/article_remote_data_source.dart'
    as _i6;
import 'package:news_app_clean_architecture/features/user_articles/data/data_sources/remote/cloudinary_service.dart'
    as _i7;
import 'package:news_app_clean_architecture/features/user_articles/data/models/user_article_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserArticleModel_1 extends _i1.SmartFake
    implements _i3.UserArticleModel {
  _FakeUserArticleModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.UserModel?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i2.UserModel?>.empty(),
      ) as _i5.Stream<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<_i2.UserModel> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i2.UserModel?>.value(),
      ) as _i5.Future<_i2.UserModel?>);

  @override
  _i5.Future<_i2.UserModel> updateProfile({
    required String? userId,
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i5.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #userId: userId,
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserModel>);
}

/// A class which mocks [ArticleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRemoteDataSource extends _i1.Mock
    implements _i6.ArticleRemoteDataSource {
  MockArticleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserArticleModel> createArticle(
          _i3.UserArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArticle,
          [article],
        ),
        returnValue:
            _i5.Future<_i3.UserArticleModel>.value(_FakeUserArticleModel_1(
          this,
          Invocation.method(
            #createArticle,
            [article],
          ),
        )),
      ) as _i5.Future<_i3.UserArticleModel>);

  @override
  _i5.Future<_i3.UserArticleModel> updateArticle(
          _i3.UserArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArticle,
          [article],
        ),
        returnValue:
            _i5.Future<_i3.UserArticleModel>.value(_FakeUserArticleModel_1(
          this,
          Invocation.method(
            #updateArticle,
            [article],
          ),
        )),
      ) as _i5.Future<_i3.UserArticleModel>);

  @override
  _i5.Future<void> deleteArticle(String? articleId) => (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [articleId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserArticleModel?> getArticleById(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [articleId],
        ),
        returnValue: _i5.Future<_i3.UserArticleModel?>.value(),
      ) as _i5.Future<_i3.UserArticleModel?>);

  @override
  _i5.Future<List<_i3.UserArticleModel>> getPublishedArticles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublishedArticles,
          [],
        ),
        returnValue: _i5.Future<List<_i3.UserArticleModel>>.value(
            <_i3.UserArticleModel>[]),
      ) as _i5.Future<List<_i3.UserArticleModel>>);

  @override
  _i5.Future<List<_i3.UserArticleModel>> getUserArticles(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArticles,
          [userId],
        ),
        returnValue: _i5.Future<List<_i3.UserArticleModel>>.value(
            <_i3.UserArticleModel>[]),
      ) as _i5.Future<List<_i3.UserArticleModel>>);

  @override
  _i5.Future<List<_i3.UserArticleModel>> getArticlesByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i3.UserArticleModel>>.value(
            <_i3.UserArticleModel>[]),
      ) as _i5.Future<List<_i3.UserArticleModel>>);

  @override
  _i5.Future<_i3.UserArticleModel> publishArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishArticle,
          [articleId],
        ),
        returnValue:
            _i5.Future<_i3.UserArticleModel>.value(_FakeUserArticleModel_1(
          this,
          Invocation.method(
            #publishArticle,
            [articleId],
          ),
        )),
      ) as _i5.Future<_i3.UserArticleModel>);

  @override
  _i5.Future<_i3.UserArticleModel> unpublishArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpublishArticle,
          [articleId],
        ),
        returnValue:
            _i5.Future<_i3.UserArticleModel>.value(_FakeUserArticleModel_1(
          this,
          Invocation.method(
            #unpublishArticle,
            [articleId],
          ),
        )),
      ) as _i5.Future<_i3.UserArticleModel>);
}

/// A class which mocks [CloudinaryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryService extends _i1.Mock implements _i7.CloudinaryService {
  MockCloudinaryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> uploadImage(
    _i8.File? imageFile, {
    String? folder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [imageFile],
          {#folder: folder},
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFile],
            {#folder: folder},
          ),
        )),
      ) as _i5.Future<String>);
}
