// Mocks generated by Mockito 5.4.4 from annotations
// in news_app_clean_architecture/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:news_app_clean_architecture/core/resources/data_state.dart'
    as _i2;
import 'package:news_app_clean_architecture/features/auth/data/data_sources/remote/auth_remote_data_source.dart'
    as _i11;
import 'package:news_app_clean_architecture/features/auth/data/models/user_model.dart'
    as _i3;
import 'package:news_app_clean_architecture/features/auth/domain/entities/user.dart'
    as _i7;
import 'package:news_app_clean_architecture/features/auth/domain/repository/auth_repository.dart'
    as _i5;
import 'package:news_app_clean_architecture/features/user_articles/data/data_sources/remote/article_remote_data_source.dart'
    as _i12;
import 'package:news_app_clean_architecture/features/user_articles/data/data_sources/remote/cloudinary_service.dart'
    as _i13;
import 'package:news_app_clean_architecture/features/user_articles/data/models/user_article_model.dart'
    as _i4;
import 'package:news_app_clean_architecture/features/user_articles/domain/entities/user_article.dart'
    as _i9;
import 'package:news_app_clean_architecture/features/user_articles/domain/repository/user_article_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserArticleModel_2 extends _i1.SmartFake
    implements _i4.UserArticleModel {
  _FakeUserArticleModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i7.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i7.UserEntity?>.empty(),
      ) as _i6.Stream<_i7.UserEntity?>);

  @override
  _i6.Future<_i2.DataState<_i7.UserEntity>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.DataState<_i7.UserEntity>>.value(
            _FakeDataState_0<_i7.UserEntity>(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i7.UserEntity>>);

  @override
  _i6.Future<_i2.DataState<_i7.UserEntity>> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i6.Future<_i2.DataState<_i7.UserEntity>>.value(
            _FakeDataState_0<_i7.UserEntity>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i7.UserEntity>>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.UserEntity?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i7.UserEntity?>.value(),
      ) as _i6.Future<_i7.UserEntity?>);

  @override
  _i6.Future<_i2.DataState<_i7.UserEntity>> updateProfile({
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i6.Future<_i2.DataState<_i7.UserEntity>>.value(
            _FakeDataState_0<_i7.UserEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i7.UserEntity>>);
}

/// A class which mocks [UserArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserArticleRepository extends _i1.Mock
    implements _i8.UserArticleRepository {
  MockUserArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.DataState<_i9.UserArticleEntity>> createArticle(
          _i9.UserArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArticle,
          [article],
        ),
        returnValue: _i6.Future<_i2.DataState<_i9.UserArticleEntity>>.value(
            _FakeDataState_0<_i9.UserArticleEntity>(
          this,
          Invocation.method(
            #createArticle,
            [article],
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i9.UserArticleEntity>>);

  @override
  _i6.Future<_i2.DataState<_i9.UserArticleEntity>> updateArticle(
          _i9.UserArticleEntity? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArticle,
          [article],
        ),
        returnValue: _i6.Future<_i2.DataState<_i9.UserArticleEntity>>.value(
            _FakeDataState_0<_i9.UserArticleEntity>(
          this,
          Invocation.method(
            #updateArticle,
            [article],
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i9.UserArticleEntity>>);

  @override
  _i6.Future<_i2.DataState<void>> deleteArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [articleId],
        ),
        returnValue:
            _i6.Future<_i2.DataState<void>>.value(_FakeDataState_0<void>(
          this,
          Invocation.method(
            #deleteArticle,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i2.DataState<void>>);

  @override
  _i6.Future<_i2.DataState<_i9.UserArticleEntity>> getArticleById(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [articleId],
        ),
        returnValue: _i6.Future<_i2.DataState<_i9.UserArticleEntity>>.value(
            _FakeDataState_0<_i9.UserArticleEntity>(
          this,
          Invocation.method(
            #getArticleById,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i9.UserArticleEntity>>);

  @override
  _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>
      getPublishedArticles() => (super.noSuchMethod(
            Invocation.method(
              #getPublishedArticles,
              [],
            ),
            returnValue:
                _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>.value(
                    _FakeDataState_0<List<_i9.UserArticleEntity>>(
              this,
              Invocation.method(
                #getPublishedArticles,
                [],
              ),
            )),
          ) as _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>);

  @override
  _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>> getUserArticles(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArticles,
          [userId],
        ),
        returnValue:
            _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>.value(
                _FakeDataState_0<List<_i9.UserArticleEntity>>(
          this,
          Invocation.method(
            #getUserArticles,
            [userId],
          ),
        )),
      ) as _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>);

  @override
  _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>> getArticlesByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesByCategory,
          [category],
        ),
        returnValue:
            _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>.value(
                _FakeDataState_0<List<_i9.UserArticleEntity>>(
          this,
          Invocation.method(
            #getArticlesByCategory,
            [category],
          ),
        )),
      ) as _i6.Future<_i2.DataState<List<_i9.UserArticleEntity>>>);

  @override
  _i6.Future<_i2.DataState<_i9.UserArticleEntity>> publishArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishArticle,
          [articleId],
        ),
        returnValue: _i6.Future<_i2.DataState<_i9.UserArticleEntity>>.value(
            _FakeDataState_0<_i9.UserArticleEntity>(
          this,
          Invocation.method(
            #publishArticle,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i9.UserArticleEntity>>);

  @override
  _i6.Future<_i2.DataState<_i9.UserArticleEntity>> unpublishArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpublishArticle,
          [articleId],
        ),
        returnValue: _i6.Future<_i2.DataState<_i9.UserArticleEntity>>.value(
            _FakeDataState_0<_i9.UserArticleEntity>(
          this,
          Invocation.method(
            #unpublishArticle,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i2.DataState<_i9.UserArticleEntity>>);

  @override
  _i6.Future<_i2.DataState<String>> uploadImage(_i10.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [imageFile],
        ),
        returnValue:
            _i6.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFile],
          ),
        )),
      ) as _i6.Future<_i2.DataState<String>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i11.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i3.UserModel?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i3.UserModel?>.empty(),
      ) as _i6.Stream<_i3.UserModel?>);

  @override
  _i6.Future<_i3.UserModel> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<_i3.UserModel> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i6.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i3.UserModel?>.value(),
      ) as _i6.Future<_i3.UserModel?>);

  @override
  _i6.Future<_i3.UserModel> updateProfile({
    required String? userId,
    String? displayName,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i6.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #userId: userId,
              #displayName: displayName,
              #photoUrl: photoUrl,
            },
          ),
        )),
      ) as _i6.Future<_i3.UserModel>);
}

/// A class which mocks [ArticleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRemoteDataSource extends _i1.Mock
    implements _i12.ArticleRemoteDataSource {
  MockArticleRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.UserArticleModel> createArticle(
          _i4.UserArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArticle,
          [article],
        ),
        returnValue:
            _i6.Future<_i4.UserArticleModel>.value(_FakeUserArticleModel_2(
          this,
          Invocation.method(
            #createArticle,
            [article],
          ),
        )),
      ) as _i6.Future<_i4.UserArticleModel>);

  @override
  _i6.Future<_i4.UserArticleModel> updateArticle(
          _i4.UserArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArticle,
          [article],
        ),
        returnValue:
            _i6.Future<_i4.UserArticleModel>.value(_FakeUserArticleModel_2(
          this,
          Invocation.method(
            #updateArticle,
            [article],
          ),
        )),
      ) as _i6.Future<_i4.UserArticleModel>);

  @override
  _i6.Future<void> deleteArticle(String? articleId) => (super.noSuchMethod(
        Invocation.method(
          #deleteArticle,
          [articleId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserArticleModel?> getArticleById(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [articleId],
        ),
        returnValue: _i6.Future<_i4.UserArticleModel?>.value(),
      ) as _i6.Future<_i4.UserArticleModel?>);

  @override
  _i6.Future<List<_i4.UserArticleModel>> getPublishedArticles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublishedArticles,
          [],
        ),
        returnValue: _i6.Future<List<_i4.UserArticleModel>>.value(
            <_i4.UserArticleModel>[]),
      ) as _i6.Future<List<_i4.UserArticleModel>>);

  @override
  _i6.Future<List<_i4.UserArticleModel>> getUserArticles(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArticles,
          [userId],
        ),
        returnValue: _i6.Future<List<_i4.UserArticleModel>>.value(
            <_i4.UserArticleModel>[]),
      ) as _i6.Future<List<_i4.UserArticleModel>>);

  @override
  _i6.Future<List<_i4.UserArticleModel>> getArticlesByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesByCategory,
          [category],
        ),
        returnValue: _i6.Future<List<_i4.UserArticleModel>>.value(
            <_i4.UserArticleModel>[]),
      ) as _i6.Future<List<_i4.UserArticleModel>>);

  @override
  _i6.Future<_i4.UserArticleModel> publishArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishArticle,
          [articleId],
        ),
        returnValue:
            _i6.Future<_i4.UserArticleModel>.value(_FakeUserArticleModel_2(
          this,
          Invocation.method(
            #publishArticle,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i4.UserArticleModel>);

  @override
  _i6.Future<_i4.UserArticleModel> unpublishArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpublishArticle,
          [articleId],
        ),
        returnValue:
            _i6.Future<_i4.UserArticleModel>.value(_FakeUserArticleModel_2(
          this,
          Invocation.method(
            #unpublishArticle,
            [articleId],
          ),
        )),
      ) as _i6.Future<_i4.UserArticleModel>);
}

/// A class which mocks [CloudinaryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryService extends _i1.Mock implements _i13.CloudinaryService {
  MockCloudinaryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> uploadImage(
    _i10.File? imageFile, {
    String? folder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [imageFile],
          {#folder: folder},
        ),
        returnValue: _i6.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [imageFile],
            {#folder: folder},
          ),
        )),
      ) as _i6.Future<String>);
}
